version: '3.7'
services:
  ldap:
    image: aesoper/openldap:v1.0.0
    privileged: true
    container_name: ldap
    restart: always
    ports:
      - "389:389"
      - "636:636"
    environment:
      LDAP_LOG_LEVEL: "256"
      LDAP_TLS_ENABLED: true
    volumes:
      - ./testdata/assets/config/mirror-mode/ldap:/assets/config
      - ./testdata/assets/ldif:/assets/ldif
      - ./testdata/assets/schema:/assets/schema
      - ./testdata/assets/certs:/assets/certs
    hostname: "ldap"
    domainname: "example.org"
    networks:
      - openldap

  ldap01:
    image: aesoper/openldap:v1.0.0
    privileged: true
    container_name: ldap01
    restart: always
    ports:
      - "2389:389"
      - "2636:636"
    environment:
      LDAP_LOG_LEVEL: "256"
      LDAP_TLS_ENABLED: true
    hostname: "ldap01"
    domainname: "example.org"
    volumes:
      - ./testdata/assets/config/mirror-mode/ldap01:/assets/config
      - ./testdata/assets/ldif:/assets/ldif
      - ./testdata/assets/schema:/assets/schema
      - ./testdata/assets/certs:/assets/certs
    networks:
      - openldap

#  ldap02:
#    image: aesoper/openldap:v1.0.0
#    privileged: true
#    container_name: ldap02
#    restart: always
#    ports:
#      - "3389:389"
#      - "3636:636"
#    environment:
#      LDAP_LOG_LEVEL: "256"
#      LDAP_TLS_ENABLED: true
#    volumes:
#      - ./testdata/assets/config/mirror-mode/ldap02:/assets/config
#    hostname: "ldap02"
#    domainname: "example.org"
#    networks:
#      - openldap

networks:
  openldap:
    driver: bridge
