#!/bin/bash

source /assets/functions/setenv
source /assets/functions/common
source /assets/functions/log-utils

is_not_initialized() {
  if [[ -f "$LDAP_INSTALL_LOCK" ]]; then
    if [ -z "$(ls -A -I lost+found --ignore=.* "$LDAP_DB_DIR")" ] &&
      [ -z "$(ls -A -I lost+found --ignore=.* "$LDAP_CONFIG_DIR")" ]; then
      true
    else
      false
    fi
  else
    true
  fi
}

mark_initialized() {
  touch "$LDAP_INSTALL_LOCK"
}


is_ldap_not_running() {
    ! is_ldap_running
}

is_ldap_running() {
    local pid
    pid="$(get_pid_from_file "${LDAP_RUN_PID_FILE}")"
    if [[ -n "${pid}" ]]; then
        is_service_running "${pid}"
    else
        false
    fi
}