#!/usr/bin/with-contenv bash

set +x

FONT_RED="$(printf '\033[38;5;1m')"
FONT_GREEN="$(printf '\033[38;5;2m')"
FONT_YELLOW="$(printf '\033[38;5;3m')"
FONT_BLUE="$(printf '\034[0;33m')"
FONT_NORMAL="$(printf '\033[0m')"
FONT_CYAN="$(printf '\033[38;5;6m')"

error() {
    echo "${FONT_RED}ERROR: $*${FONT_NORMAL}"
}

warn() {
     echo "${FONT_YELLOW}WARNING: $*${FONT_NORMAL}"
}

info() {
    echo "${FONT_GREEN}INFO: $*${FONT_NORMAL}"
}

debug() {
    echo "${FONT_BLUE}$*${FONT_NORMAL}"
}

log(){
    echo "${FONT_CYAN}$*${FONT_NORMAL}"
}
