#!/bin/bash

source /assets/functions/common

# Set the default values for the environment variables if not set

export LDAP_DB_DIR="/var/lib/ldap"
export LDAP_ETC_DIR="/etc/ldap"
export LDAP_ETC_CONF_FILE="$LDAP_ETC_DIR/ldap.conf"
export LDAP_ETC_CONF_FILE_BACKUP="$LDAP_ETC_DIR/ldap.conf.bak"
export LDAP_CONFIG_DIR="$LDAP_ETC_DIR/slapd.d"
export LDAP_SCHEMA_DIR="$LDAP_ETC_DIR/schema"
export LDAP_RUN_DIR="/var/run/slapd"
export LDAP_RUN_PID_FILE="$LDAP_RUN_DIR/slapd.pid"
export LDAP_RUN_ARGS_FILE="$LDAP_RUN_DIR/slapd.args"

export LDAP_SHARE_DIR="/usr/share/ldap"
export LDAP_LDAP_INSTALL_LOCK_DIR="$LDAP_SHARE_DIR/lock"
export LDAP_INSTALL_LOCK="$LDAP_LDAP_INSTALL_LOCK_DIR/install.lock"
export LDAP_TLS_INSTALL_LOCK_FILE="$LDAP_LDAP_INSTALL_LOCK_DIR/tls.lock"
export LDAP_REPLICATION_INSTALL_LOCK_FILE="$LDAP_LDAP_INSTALL_LOCK_DIR/replicator.lock"
export LDAP_CUSTOM_LDIF_INSTALL_LOCK_FILE="$LDAP_LDAP_INSTALL_LOCK_DIR/custom-ldif.lock"
export LDAP_CUSTOM_SCHEMA_INSTALL_LOCK_FILE="$LDAP_LDAP_INSTALL_LOCK_DIR/custom-schema.lock"


export LDAP_SHARE_LDIF_DIR="$LDAP_SHARE_DIR/ldif" # after install yourself ldif files, it will be copied to this directory, so you must makesure ldif filename is unique.
export LDAP_SHARE_LDIF_CUSTOM_DIR="$LDAP_SHARE_LDIF_DIR/custom" # after install yourself ldif files, it will be copied to this directory, so you must makesure ldif filename is unique.
export LDAP_SHARE_LDIF_BOOTSTRAP_DIR="$LDAP_SHARE_LDIF_DIR/bootstrap" # after install yourself ldif files, it will be copied to this directory, so you must makesure ldif filename is unique.

# tls
export LDAP_TLS_CRT_DIR="/assets/certs"

# ldif
export LDAP_LDIF_CUSTOM_DIR="/assets/ldif"
export LDAP_SCHEMA_CUSTOM_DIR="/assets/schema"



# config
export LDAP_CUSTOM_ENV_DIR="/assets/config"

# log
export LDAP_LOG_DIR="/var/log/slapd"
export LDAP_DB_ACCESS_LOG_DIR="${LDAP_LOG_DIR}/accesslog"


# auditlog
export LDAP_AUDIT_LOG_FILE=${LDAP_AUDIT_LOG_FILE:-"$LDAP_LOG_DIR/auditlog.log"}

# environment
export LDAP_DEFAULT_ENV_DIR="/environment/default"


ensure_dir_exists "$LDAP_CUSTOM_ENV_DIR"
#ulimit -n 1024
# load default config to environment
source /usr/bin/load_yaml_env -p $LDAP_DEFAULT_ENV_DIR -p $LDAP_CUSTOM_ENV_DIR

#env | grep LDAP


