#!/usr/bin/with-contenv bash

source /assets/functions/setenv
source /assets/functions/common
source /assets/functions/log-utils
source /assets/functions/ldap

LDAP_OPENLDAP_UID=${LDAP_OPENLDAP_UID:-911}
LDAP_OPENLDAP_GID=${LDAP_OPENLDAP_GID:-911}

LDAP_UIDGID_CHANGED=false

info "Set uid and gid for openldap user and group"

if is_not_initialized; then
  info "get current openldap uid/gid info inside container"
  CUR_USER_UID=$(id -u openldap)
  CUR_USER_GID=$(id -g openldap)

  if [ "$LDAP_OPENLDAP_UID" != "$CUR_USER_UID" ]; then
    info "change openldap uid from $CUR_USER_UID to $LDAP_OPENLDAP_UID"
    usermod -o -u "$LDAP_OPENLDAP_UID" openldap
    LDAP_UIDGID_CHANGED=true
  fi
  if [ "$LDAP_OPENLDAP_GID" != "$CUR_USER_GID" ]; then
    info "change openldap gid from $CUR_USER_GID to $LDAP_OPENLDAP_GID"
    groupmod -o -g "$LDAP_OPENLDAP_GID" openldap
    LDAP_UIDGID_CHANGED=true
  fi
fi

info '-------------------------------------'
info 'openldap GID/UID'
info '-------------------------------------'
info "User uid:    $(id -u openldap)"
info "User gid:    $(id -g openldap)"
info "uid/gid changed: ${LDAP_UIDGID_CHANGED}"
info '-------------------------------------'
