#!/command/with-contenv bash

set -e

source /assets/functions/setenv
source /assets/functions/common
source /assets/functions/log-utils
source /assets/functions/ldap


if is_not_initialized; then
    info "dpkg-reconfigure slapd 2.5.13"

    LDAP_ADMIN_PASSWORD_ENCRYPTED=$(slappasswd -s "$LDAP_ADMIN_PASSWORD")

    cat <<EOL | debconf-set-selections
slapd slapd/password1 password ${LDAP_ADMIN_PASSWORD_ENCRYPTED}
slapd slapd/internal/generated_adminpw password ${LDAP_ADMIN_PASSWORD_ENCRYPTED}
slapd slapd/internal/adminpw password ${LDAP_ADMIN_PASSWORD_ENCRYPTED}
slapd slapd/password2 password ${LDAP_ADMIN_PASSWORD_ENCRYPTED}
slapd slapd/invalid_config boolean true
slapd slapd/dump_database_destdir string /var/backups/slapd-VERSION
slapd slapd/move_old_database boolean true
slapd slapd/dump_database select when needed
slapd slapd/no_configuration boolean false
slapd slapd/domain string ${LDAP_DOMAIN}
slapd slapd/purge_database boolean false
slapd shared/organization string ${LDAP_ORGANISATION}
EOL

    dpkg-reconfigure -f noninteractive slapd

    info "dpkg-reconfigure slapd 2.5.13 done"
fi