#!/usr/bin/with-contenv bash

set -e

source /assets/functions/setenv
source /assets/functions/common
source /assets/functions/log-utils
source /assets/functions/ldap

if is_not_initialized; then
  info "Add admin user to ldap"

  LDAP_ADMIN_PASSWORD_ENCRYPTED=$(slappasswd -s "$LDAP_ADMIN_PASSWORD")
  LDAP_CONFIG_PASSWORD_ENCRYPTED=$(slappasswd -s "$LDAP_CONFIG_PASSWORD")
  ADMIN_USER_DN="cn=${LDAP_ADMIN_USERNAME},${LDAP_BASE_DN}"

  ldapmodify -Q -Y EXTERNAL -H ldapi:///  <<EOF
# backend config olcRootDN change
dn: olcDatabase={1}${LDAP_BACKEND},cn=config
changetype: modify
replace: olcSuffix
olcSuffix: ${LDAP_BASE_DN}

# backend config olcRootDN change
dn: olcDatabase={1}${LDAP_BACKEND},cn=config
changetype: modify
replace: olcRootDN
olcRootDN: ${ADMIN_USER_DN}

# backend config olcRootPW change
dn: olcDatabase={1}${LDAP_BACKEND},cn=config
changetype: modify
replace: olcRootPW
olcRootPW: ${LDAP_ADMIN_PASSWORD_ENCRYPTED}
EOF

fi