#!/command/with-contenv bash

set -e

source /assets/functions/setenv
source /assets/functions/common
source /assets/functions/log-utils
source /assets/functions/ldap

if is_not_initialized && is_boolean_yes "$LDAP_READONLY_USER_ENABLED"; then
  info "Add readonly user to slapd"

  LDAP_READONLY_USER_DN="cn=${LDAP_READONLY_USER_USERNAME},${LDAP_BASE_DN}"
  LDAP_READONLY_USER_PASSWORD_ENCRYPTED=$(slappasswd -s "${LDAP_READONLY_USER_PASSWORD}")

  ldapmodify -Y EXTERNAL -H ldapi:/// <<EOF
dn: ${LDAP_READONLY_USER_DN}
changetype: add
objectClass: simpleSecurityObject
objectClass: organizationalRole
cn: ${LDAP_READONLY_USER_USERNAME}
description: for sssd, readonly user
userPassword: ${LDAP_READONLY_USER_PASSWORD_ENCRYPTED}
EOF

  info "Add readonly user to slapd done"

  info "Add readonly user to slapd access control"

  ADMIN_USER_DN="cn=${LDAP_ADMIN_USERNAME},${LDAP_BASE_DN}"
  READONLY_USER_DN="cn=${LDAP_READONLY_USER_USERNAME},${LDAP_BASE_DN}"

  ldapmodify -Y EXTERNAL -H ldapi:/// <<EOF
dn: olcDatabase={1}${LDAP_BACKEND},cn=config
changetype: modify
replace: olcAccess
olcAccess: {0}to * by dn.exact=gidNumber=0+uidNumber=0,cn=peercred,cn=external,cn=auth manage by * break
olcAccess: {1}to attrs=userPassword,shadowLastChange
  by dn="${ADMIN_USER_DN}" write
  by dn="${READONLY_USER_DN}" read
  by self write
  by anonymous auth
  by * none
olcAccess: {2}to *
  by dn="${ADMIN_USER_DN}" write
  by dn="${READONLY_USER_DN}" read
  by self write
  by anonymous auth
  by * none
EOF

  info "Add readonly user to slapd access control done"

fi
