#!/usr/bin/with-contenv bash

set -e

source /assets/functions/setenv
source /assets/functions/common
source /assets/functions/log-utils
source /assets/functions/ldap

if is_not_initialized; then
  info "set logging level to $LDAP_LOG_LEVEL"

  cat <<EOF |  ldapmodify -Q -Y EXTERNAL -H ldapi:///
dn: cn=config
changetype: modify
replace: olcLogLevel
olcLogLevel: ${LDAP_LOG_LEVEL}
EOF

  info "set logging level to $LDAP_LOG_LEVEL done"
fi