#!/usr/bin/with-contenv bash

set -e

source /assets/functions/setenv
source /assets/functions/common
source /assets/functions/log-utils
source /assets/functions/ldap

if is_not_initialized; then
  info "Add monitor to slapd"

  ADMIN_USER_DN="cn=${LDAP_ADMIN_USERNAME},${LDAP_BASE_DN}"

  cat <<EOF | ldapadd -Q -Y EXTERNAL -H ldapi:///
dn: olcDatabase={2}monitor,cn=config
objectClass: olcDatabaseConfig
olcDatabase: monitor
olcAccess: {0}to * by dn.base="gidNumber=0+uidNumber=0,cn=peercred,cn=external,cn=auth" read by dn.base="${ADMIN_USER_DN}" read by * none
olcAccess: {1}to * by self write by dn="${ADMIN_USER_DN}" write by * none
EOF

  info "Add monitor to slapd done"
fi
