#!/usr/bin/with-contenv bash

set -e

source /assets/functions/setenv
source /assets/functions/common
source /assets/functions/log-utils
source /assets/functions/ldap

if is_not_initialized; then
  info "add accesslog"

  ADMIN_USER_DN="cn=${LDAP_ADMIN_USERNAME},${LDAP_BASE_DN}"

  cat <<EOF | ldapmodify -Q -Y EXTERNAL -H ldapi:///
dn: cn=module{0},cn=config
changetype: modify
add: olcModuleLoad
olcModuleLoad: accesslog

## Accesslog database definitions
#dn: olcDatabase={3}${LDAP_BACKEND},cn=config
#changetype: add
#objectClass: olcDatabaseConfig
#objectClass: olcMdbConfig
#olcDatabase: {3}${LDAP_BACKEND}
#olcDbDirectory: ${LDAP_DB_DIR}
#olcSuffix: cn=accesslog
#olcRootDN: ${ADMIN_USER_DN}
#olcDbIndex: objectClass eq
#olcDbIndex: reqResult eq
#olcDbIndex: reqEnd eq
#olcDbIndex: reqStart eq
#olcDbIndex: reqType eq
#olcDbIndex: entryCSN eq
#olcDbIndex: reqDN eq
#olcAccess: to * by dn.base="gidNumber=0+uidNumber=0,cn=peercred,cn=external,cn=auth" read by dn.base="${ADMIN_USER_DN}" read by * none
#
#dn: olcOverlay=syncprov,olcDatabase={3}${LDAP_BACKEND},cn=config
#changetype: add
#objectClass: olcOverlayConfig
#objectClass: olcSyncProvConfig
#olcOverlay: syncprov
#olcSpNoPresent: TRUE
#olcSpReloadHint: TRUE
#
## Accesslog overlay definitions for the primary db
#dn: olcOverlay=accesslog,olcDatabase={1}${LDAP_BACKEND},cn=config
#changetype: add
#objectClass: olcOverlayConfig
#objectClass: olcAccessLogConfig
#olcOverlay: accesslog
#olcAccesslogDB: cn=accesslog
#olcAccessLogOps: writes
#olcAccessLogSuccess: TRUE
#olcAccessLogPurge: 07+00:00 01+00:00
EOF

  info "add accesslog done"


  info "add accesslog done"
fi
