#!/command/with-contenv bash

set -e

source /assets/functions/setenv
source /assets/functions/common
source /assets/functions/log-utils
source /assets/functions/ldap

LDAP_TLS_CA_CRT_FILE="$LDAP_TLS_CRT_DIR/$LDAP_TLS_CA_CRT_FILENAME"
LDAP_TLS_CRT_FILE="$LDAP_TLS_CRT_DIR/$LDAP_TLS_CRT_FILENAME"
LDAP_TLS_KEY_FILE="$LDAP_TLS_CRT_DIR/$LDAP_TLS_KEY_FILENAME"
LDAP_TLS_DH_PARAM_PATH="$LDAP_TLS_CRT_DIR/$LDAP_TLS_DH_PARAM_FILENAME"

if [ ! -f "$LDAP_TLS_INSTALL_LOCK_FILE" ]; then
  info "Add TLS to slapd"

  if is_boolean_yes "$LDAP_TLS_ENABLED"; then

    if [ ! -f "$LDAP_TLS_CA_CRT_FILE" ]; then
      error "TLS CA certificate file not found: $LDAP_TLS_CA_CRT_FILE"
      exit 1
    fi

    if [ ! -f "$LDAP_TLS_CRT_FILE" ]; then
      error "TLS certificate file not found: $LDAP_TLS_CRT_FILE"
      exit 1
    fi

    if [ ! -f "$LDAP_TLS_KEY_FILE" ]; then
      error "TLS key file not found: $LDAP_TLS_KEY_FILE"
      exit 1
    fi

    if [ ! -f "$LDAP_TLS_DH_PARAM_PATH" ]; then
      error "TLS DH param file not found: $LDAP_TLS_DH_PARAM_PATH"
      exit 1
    fi

    chown -R openldap:openldap "$LDAP_TLS_CA_CRT_FILE"
    chown -R openldap:openldap "$LDAP_TLS_CRT_FILE"
    chown -R openldap:openldap "$LDAP_TLS_KEY_FILE"

    chmod 400 "$LDAP_TLS_CA_CRT_FILE"
    chmod 400 "$LDAP_TLS_CRT_FILE"
    chmod 400 "$LDAP_TLS_KEY_FILE"

    _URI=""

    if [ -z "$LDAP_TLS_PROVIDER_URI" ]; then
      FQDN=$(/bin/hostname --fqdn)
      _URI="ldap://$FQDN"
    fi

    ldap_tls --change_type replace --ca_file "$LDAP_TLS_CA_CRT_FILE" \
      --cert_file "$LDAP_TLS_CRT_FILE" \
      --cert_key_file "$LDAP_TLS_KEY_FILE" \
      --dh_file "$LDAP_TLS_DH_PARAM_PATH" \
      --ciphers "$LDAP_TLS_CIPHER_SUITE" \
      --verify_client "$LDAP_TLS_VERIFY_CLIENT" \
      --rewrite_conf "$LDAP_TLS_LDAP_TLS_IS_CLIENT" \
      --uri "$_URI" \
      --base_dn "$LDAP_BASE_DN"

    if is_boolean_yes "$LDAP_TLS_SHARE_CA_CERTIFICATES"; then
      cp -f "$LDAP_TLS_CA_CRT_FILE" /usr/local/share/ca-certificates/
      update-ca-certificates
    fi

  fi

  info "Add TLS to slapd done"
  touch "$LDAP_TLS_INSTALL_LOCK_FILE"
fi
