#!/command/with-contenv bash

set -e

source /assets/functions/setenv
source /assets/functions/common
source /assets/functions/log-utils
source /assets/functions/ldap

if is_not_initialized && [ ! -f "$LDAP_REPLICATION_INSTALL_LOCK_FILE" ]; then
  if is_boolean_yes "$LDAP_REPLICATION_ENABLED" && [ "$LDAP_REPLICATION_MODE" = "MultiMaster" ]; then

    info "enable replication multi-master"

    ADMIN_USER_DN="cn=${LDAP_ADMIN_USERNAME},${LDAP_BASE_DN}"

    LDAP_REPLICATION_DB_SYNC_REPL_PLACEHOLDER="{{ LDAP_REPLICATION_DB_SYNC_REPL_PLACEHOLDER }}"
    LDAP_REPLICATION_HOSTS_PLACEHOLDER="{{ LDAP_REPLICATION_HOSTS_PLACEHOLDER }}"
    LDAP_REPLICATION_CONFIG_SYNC_REPL_PLACEHOLDER="{{ LDAP_REPLICATION_CONFIG_SYNC_REPL_PLACEHOLDER }}"

    count=0
    NODE_SERVER_ID=""
    while true; do
      host="LDAP_REPLICATION_HOSTS_${count}"
      if [ -z "${!host}" ]; then
        error "LDAP_REPLICATION_HOSTS[${count}] is empty"
        exit 1
      fi

      SERVER_ID=$((100 + count))

      _hostname=$(echo "${!host}" | sed -e "s|.*//||g" | sed -e "s|:.*||g")
      _FQDN="$(/bin/hostname --fqdn)"
      _HOSTNAME="$(/bin/hostname)"

      if [ "${_hostname}" = "${_FQDN}" ] || [ "${_hostname}" = "${_HOSTNAME}" ]; then
        info "Found node server id: ${SERVER_ID}"
        NODE_SERVER_ID="${SERVER_ID}"
      fi

      DB_SYNC_RID=$((100 + count))
      CONFIG_SYNC_RID=$((500 + count))

      ENV_DB_SYNC_REPL_VALUE=$(echo "{{ PLACEHOLDER }} ${LDAP_REPLICATION_DB_SYNC_REPL}" | sed -e "s|rid=\S*\s*||g" | sed -e "s|provider=\S*\s*||g" | sed -e "s|{{ PLACEHOLDER }}|rid=${DB_SYNC_RID} provider=${!host}|g")
      ENV_CONFIG_SYNC_REPL_VALUE=$(echo "{{ PLACEHOLDER }} ${LDAP_REPLICATION_CONFIG_SYNC_REPL}" | sed -e "s|rid=\S*\s*||g" | sed -e "s|provider=\S*\s*||g" | sed -e "s|{{ PLACEHOLDER }}|rid=${CONFIG_SYNC_RID} provider=${!host}|g")

      # shellcheck disable=SC2001
      LDAP_REPLICATION_HOSTS_PLACEHOLDER=$(echo "${LDAP_REPLICATION_HOSTS_PLACEHOLDER}" | sed -e "s|{{ LDAP_REPLICATION_HOSTS_PLACEHOLDER }}|olcServerID: ${SERVER_ID} ${!host}\n{{ LDAP_REPLICATION_HOSTS_PLACEHOLDER }}|g")
      # shellcheck disable=SC2001
      LDAP_REPLICATION_DB_SYNC_REPL_PLACEHOLDER=$(echo "${LDAP_REPLICATION_DB_SYNC_REPL_PLACEHOLDER}" | sed -e "s|{{ LDAP_REPLICATION_DB_SYNC_REPL_PLACEHOLDER }}|olcSyncRepl: ${ENV_DB_SYNC_REPL_VALUE}\n{{ LDAP_REPLICATION_DB_SYNC_REPL_PLACEHOLDER }}|g")
      # shellcheck disable=SC2001
      LDAP_REPLICATION_CONFIG_SYNC_REPL_PLACEHOLDER=$(echo "${LDAP_REPLICATION_CONFIG_SYNC_REPL_PLACEHOLDER}" | sed -e "s|{{ LDAP_REPLICATION_CONFIG_SYNC_REPL_PLACEHOLDER }}|olcSyncRepl: ${ENV_CONFIG_SYNC_REPL_VALUE}\n{{ LDAP_REPLICATION_CONFIG_SYNC_REPL_PLACEHOLDER }}|g")

      count=$((count + 1))
      next_host="LDAP_REPLICATION_HOSTS_${count}"
      if [ -z "${!next_host}" ]; then
        break
      fi

    done

    if [ -z "${NODE_SERVER_ID}" ]; then
      error "NODE_SERVER_ID is empty"
      exit 1
    fi

    info "[${HOSTNAME}]NODE_SERVER_ID: ${NODE_SERVER_ID}"

    LDAP_REPLICATION_HOSTS_PLACEHOLDER=$(echo "${LDAP_REPLICATION_HOSTS_PLACEHOLDER}" | sed -e "/{{ LDAP_REPLICATION_HOSTS_PLACEHOLDER }}/d")
    LDAP_REPLICATION_DB_SYNC_REPL_PLACEHOLDER=$(echo "${LDAP_REPLICATION_DB_SYNC_REPL_PLACEHOLDER}" | sed -e "/{{ LDAP_REPLICATION_DB_SYNC_REPL_PLACEHOLDER }}/d")
    LDAP_REPLICATION_CONFIG_SYNC_REPL_PLACEHOLDER=$(echo "${LDAP_REPLICATION_CONFIG_SYNC_REPL_PLACEHOLDER}" | sed -e "/{{ LDAP_REPLICATION_CONFIG_SYNC_REPL_PLACEHOLDER }}/d")

    error "LDAP_REPLICATION_HOSTS_PLACEHOLDER: ${LDAP_REPLICATION_HOSTS_PLACEHOLDER}"
    error "LDAP_REPLICATION_DB_SYNC_REPL_PLACEHOLDER: ${LDAP_REPLICATION_DB_SYNC_REPL_PLACEHOLDER}"
    error "LDAP_REPLICATION_CONFIG_SYNC_REPL_PLACEHOLDER: ${LDAP_REPLICATION_CONFIG_SYNC_REPL_PLACEHOLDER}"

    if [ -z "${LDAP_REPLICATION_DB_SYNC_REPL_PLACEHOLDER}" ]; then
      error "LDAP_REPLICATION_DB_SYNC_REPL_PLACEHOLDER is empty"
      exit 1
    fi

    if [ -z "${LDAP_REPLICATION_CONFIG_SYNC_REPL_PLACEHOLDER}" ]; then
      error "LDAP_REPLICATION_CONFIG_SYNC_REPL_PLACEHOLDER is empty"
      exit 1
    fi

    if [ -z "${LDAP_REPLICATION_HOSTS_PLACEHOLDER}" ]; then
      error "LDAP_REPLICATION_HOSTS_PLACEHOLDER is empty"
      exit 1
    fi

    info "enable syncprov module"

    cat <<EOF | ldapmodify -Q -Y EXTERNAL -H ldapi:///
dn: cn=module{0},cn=config
changetype: modify
add: olcModuleLoad
olcModuleLoad: syncprov
EOF

    info "enable syncprov module done"

    info "set olcServerID"

    cat <<EOF | ldapmodify -Q -Y EXTERNAL -H ldapi:///
dn: cn=config
changeType: modify
add: olcServerID
olcServerID: ${NODE_SERVER_ID}
EOF

    info "set olcServerID done"

    info "Update olcServerID with provider URI for replication"

    cat <<EOF | ldapmodify -Q -Y EXTERNAL -H ldapi:///
dn: cn=config
changetype: modify
replace: olcServerID
${LDAP_REPLICATION_HOSTS_PLACEHOLDER}
EOF

    info "Update olcServerID with provider URI for replication done"

    info "Add olcOverlay=syncprov to config"

    cat <<EOF | ldapmodify -Q -Y EXTERNAL -H ldapi:///
dn: olcOverlay=syncprov,olcDatabase={0}config,cn=config
changetype: add
objectClass: olcOverlayConfig
objectClass: olcSyncProvConfig
olcOverlay: syncprov    
EOF

    info "Add olcOverlay=syncprov to config done"

    info "Add SyncRepl to the config "
    cat <<EOF | ldapmodify -Q -Y EXTERNAL -H ldapi:///
dn: olcDatabase={0}config,cn=config
changetype: modify
add: olcSyncRepl
${LDAP_REPLICATION_CONFIG_SYNC_REPL_PLACEHOLDER}
-
add: olcMirrorMode
olcMirrorMode: TRUE
EOF

    info "Add SyncRepl to the config  done"

    info "Add olcOverlay=syncprov to database"
    cat <<EOF | ldapmodify -Q -Y EXTERNAL -H ldapi:///
dn: olcOverlay=syncprov,olcDatabase={1}${LDAP_BACKEND},cn=config
changetype: add
objectClass: olcOverlayConfig
objectClass: olcSyncProvConfig
olcOverlay: syncprov
EOF

    # shellcheck disable=SC2181
    if [ $? -ne 0 ]; then
      error "Error executing ..."
      exit 1
    fi

    info "Add olcOverlay=syncprov to database done"

    info "Add SyncRepl to the database"

    cat <<EOF | ldapmodify -Q -Y EXTERNAL -H ldapi:///
dn: olcDatabase={1}${LDAP_BACKEND},cn=config
changetype: modify
add: olcSyncRepl
${LDAP_REPLICATION_DB_SYNC_REPL_PLACEHOLDER}
-
add: olcMirrorMode
olcMirrorMode: TRUE
-
add: olcLimits
olcLimits: dn.exact="${ADMIN_USER_DN}" time.soft=unlimited time.hard=unlimited size.soft=unlimited size.hard=unlimited
EOF

    info "Add SyncRepl to the database done"

    info "set provider done"
    touch "$LDAP_REPLICATION_INSTALL_LOCK_FILE"
  fi

fi
