#!/usr/bin/with-contenv bash

set -e

source /assets/functions/setenv
source /assets/functions/common
source /assets/functions/log-utils
source /assets/functions/ldap

if is_not_initialized; then
  info "Add dyngroup overlay to slapd"

  ldapadd -Y EXTERNAL -H ldapi:/// -f "$LDAP_SCHEMA_DIR"/dyngroup.ldif


  cat <<EOF | ldapadd -Y EXTERNAL -H ldapi:///
#dn: cn=module{0},cn=config
#changetype: modify
#add: olcModuleLoad
#olcModuleLoad: dyngroup


# Backend dynlist overlay
dn: cn=module{0},cn=config
changetype: modify
add: olcModuleLoad
olcModuleLoad: dynlist
olcModuleLoad: autogroup

# Set up dynlist overlay
dn: olcOverlay={0}dynlist,olcDatabase={1}${LDAP_BACKEND},cn=config
objectClass: olcOverlayConfig
objectClass: olcDynamicList
olcOverlay: {0}dynlist
olcDlAttrSet: {0}groupOfURLs memberURL member
#olcDlAttrSet: {0}groupOfURLs labeledURI member

# Set up the autogroup overlay
dn: olcOverlay=autogroup,olcDatabase={1}${LDAP_BACKEND},cn=config
objectClass: olcOverlayConfig
objectClass: olcAutomaticGroups
olcOverlay: autogroup
olcAGattrSet: {0}groupOfURLs memberURL member
#olcDlAttrSet: {0}groupOfURLs labeledURI member
olcAGmemberOfAd: memberOf
EOF


  info "Add dyngroup overlay to slapd done"

fi
