#!/usr/bin/with-contenv bash

set -e

source /assets/functions/setenv
source /assets/functions/common
source /assets/functions/log-utils
source /assets/functions/ldap



if is_not_initialized; then
  if is_boolean_yes "$LDAP_REPLICATOR_ENABLED"; then
    info "prepare replication"

    cat <<EOF | ldapmodify -Y EXTERNAL -H ldapi:///
dn: cn=module{0},cn=config
changetype: modify
add: olcModuleLoad
olcModuleLoad: syncprov
EOF

    info "prepare replication done"
  fi
fi


