#!/usr/bin/with-contenv bash

set -e

source /assets/functions/setenv
source /assets/functions/common
source /assets/functions/log-utils
source /assets/functions/ldap

if is_not_initialized; then
  info "Add admin user to ldap"

  LDAP_ADMIN_PASSWORD_ENCRYPTED=$(slappasswd -s "$LDAP_ADMIN_PASSWORD")
  LDAP_CONFIG_PASSWORD_ENCRYPTED=$(slappasswd -s "$LDAP_CONFIG_PASSWORD")

  ldapmodify -Q -Y EXTERNAL -H ldapi:///  <<EOF
# backend config olcRootDN change
dn: olcDatabase={1}${LDAP_BACKEND},cn=config
changetype: modify
replace: olcSuffix
olcSuffix: ${LDAP_BASE_DN}

# backend config olcRootDN change
dn: olcDatabase={1}${LDAP_BACKEND},cn=config
changetype: modify
replace: olcRootDN
olcRootDN: cn=admin,${LDAP_BASE_DN}

# Config password change
dn: olcDatabase={0}config,cn=config
changetype: modify
replace: olcRootPW
olcRootPW: ${LDAP_CONFIG_PASSWORD_ENCRYPTED}

# backend config olcRootPW change
dn: olcDatabase={1}${LDAP_BACKEND},cn=config
changetype: modify
replace: olcRootPW
olcRootPW: ${LDAP_ADMIN_PASSWORD_ENCRYPTED}

dn: olcDatabase={1}${LDAP_BACKEND},cn=config
changetype: modify
delete: olcAccess
-
add: olcAccess
olcAccess: {0}to * by dn.exact=gidNumber=0+uidNumber=0,cn=peercred,cn=external,cn=auth manage by * break
olcAccess: {1}to attrs=userPassword,shadowLastChange by self write by dn="cn=admin,${LDAP_BASE_DN}" write by anonymous auth by * none
olcAccess: {2}to * by self read by dn="cn=admin,${LDAP_BASE_DN}" write by * none
EOF

  info "Add admin user to ldap done"
fi

